// <auto-generated />
using ContactManager.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ContactManager.Migrations
{
    [DbContext(typeof(ContactManagerContext))]
    partial class ContactManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("ContactManager.Models.Company", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Domain");

                    b.Property<int>("FeePerHour");

                    b.Property<string>("Name");

                    b.Property<string>("Service");

                    b.Property<int>("Telephone");

                    b.Property<string>("Website");

                    b.HasKey("ID");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("ContactManager.Models.Individual", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Domain");

                    b.Property<int>("FeePerHour");

                    b.Property<string>("Forename");

                    b.Property<string>("Service");

                    b.Property<string>("Surname");

                    b.Property<int>("Telephone");

                    b.HasKey("ID");

                    b.ToTable("Individual");
                });
#pragma warning restore 612, 618
        }
    }
}
